---

- name: Copy cert files from Controller
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  loop: "{{ httpd_cert_files }}"
  loop_control: 
    label: "{{ item.src }}"
  register: file_copy

- block:
  - name: Open http port
    firewalld:
      service: 'http'
      permanent: yes
      immediate: yes
      state: enabled

  - name: Open https port
    firewalld:
      service: 'https'
      permanent: yes
      immediate: yes
      state: enabled
  tags: reverse-proxy

- name: Configure the httpd conf file for CentOS/RHEL 8
  template:
    backup: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ httpd_conf_files_8 }}"
  loop_control:
    label: "{{ item.src }}"
  notify:
    - restart httpd
  tags: reverse-proxy
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") 

- name: Configure the httpd conf file for CentOS/RHEL 7
  template:
    backup: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ httpd_conf_files_7 }}"
  loop_control:
    label: "{{ item.src }}"
  notify:
    - restart httpd
  tags: reverse-proxy
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or
        (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") 

- name: Check if index.html exists
  stat:
    path: /var/www/html/index.html
  register: index_html_exists

- name: Create index.html
  file:
    path: /var/www/html/index.html
    state: touch
    mode: 0644
    owner: apache
    group: apache  
  tags: reverse-proxy
  when: not index_html_exists.stat.exists

- name: Set SELinux HTTPD Network Connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  tags: reverse-proxy

- name: Ensure service is started
  service:
    name: httpd
    state: started
    enabled: true
  tags: reverse-proxy
