---
# defaults file for roles/ansible-ejbca-ra-nginx

ejbca_csr_dir_output: "{{ playbook_dir }}/ejbcaCSR"
ejbca_root_dir: /opt
ejbca_home: "{{ ejbca_root_dir }}/ejbca"
ejbca_sh: "{{ ejbca_home }}/bin/ejbca.sh"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
ejbca_ra_group: ejbcara
ejbca_ra_user: ejbcara

add_mgmt_ca: true

httpd_identity_info:
  id_name: ocsp01.solitude.skyrim
  id_ca_cert_file: ManagementCA.crt


httpd_conf_files:
  - src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  - src: ssl-ra.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
  - src: 00-base.conf.j2
    dest: /etc/httpd/conf.modules.d/00-base.conf
  - src: 00-dav.conf.j2
    dest: /etc/httpd/conf.modules.d/00-dav.conf
  - src: 00-lua.conf.j2
    dest: /etc/httpd/conf.modules.d/00-lua.conf
  - src: 00-proxy.conf.j2
    dest: /etc/httpd/conf.modules.d/00-proxy.conf
  - src: 01-cgi.conf.j2
    dest: /etc/httpd/conf.modules.d/01-cgi.conf
  - src: 80.conf.j2
    dest: /etc/httpd/conf.d/80.conf

httpd_cert_files:
  - src: "{{ ejbca_csr_dir_output }}/{{ httpd_identity_info.id_name }}.crt"
    dest: "/etc/pki/tls/certs/{{ httpd_identity_info.id_name }}.crt"
  - src: "{{ ejbca_csr_dir_output }}/{{ httpd_identity_info.id_name }}.key"
    dest: "/etc/pki/tls/private/{{ httpd_identity_info.id_name }}.key"
  - src: "{{ ejbca_csr_dir_output }}/{{ httpd_identity_info.id_ca_cert_file }}"
    dest: "/etc/pki/tls/certs/trusted-ca.crt"