---
# defaults file for ansible-ejbca-ra-ee
ejbca_csr_dir_output: "{{ playbook_dir }}/ejbcaCSR"
ejbca_root_dir: /opt
ejbca_home: "{{ ejbca_root_dir }}/ejbca"
ejbca_sh: "{{ ejbca_home }}/bin/ejbca.sh"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
wildfly_manage_service: true
ejbca_ra_group: ejbcara
ejbca_ra_user: ejbcara

# Used to name the Root & Sub CA templates
organizationName: Solitude
organizationNameShort: "{{ organizationName }}"
organizationDomainName: solitude.skyrim
countryName: US
superAdminCn: "27May2020 Skyrim Super Administrator"

# location to copy p12 to locally
superadmin_local_dir: ~/Desktop

# apply_indexes: If default EJBCA database indexes should be applied. Will always report change if true
# database_name: Name of EJBCA database
management_database_indexes:
  apply_indexes: true
  database_name: ejbca

ejbca_database_indexes:
  - index: "/usr/bin/mysql -u root --password={{ mariadb_root_password }} {{ management_database_indexes.database_name }} -s -e 'source {{ ejbca_home }}/doc/sql-scripts/create-index-ejbca.sql'"
  #- index: "/usr/bin/mysql -u root {{ management_database_indexes.database_name }} -s -e 'ALTER TABLE AuditRecordData row_format=compressed key_block_size=4;'"
  #- index: "/usr/bin/mysql -u root {{ management_database_indexes.database_name }} -s -e 'ALTER TABLE CertReqHistoryData row_format=compressed key_block_size=4;'"
  #- index: "/usr/bin/mysql -u root {{ management_database_indexes.database_name }} -s -e 'ALTER TABLE CRLData row_format=compressed key_block_size=16;'"
  #- index: "/usr/bin/mysql -u root {{ management_database_indexes.database_name }} -s -e 'ALTER TABLE CertificateData row_format=compressed key_block_size=8;'"
  #- index: "/usr/bin/mysql -u root {{ management_database_indexes.database_name }} -s -e 'ALTER TABLE UserData row_format=compressed key_block_size=4;'"

# If true, allows running application server service via preload
ncipher_preload: false
# Path to the preload executable
preload_path: /opt/nfast/bin/preload
# HSM PKCS#11 shared library location
hsm_shared_library: /opt/softhsm/hsm_pkcs11.so

# Database root user password. Should be encrypted with Ansible vault
database_rootuser_password: "{{ encrypted_database_rootuser_password | default('root') }}"

# List of certification authorities that should be imported using CLI
# caname: CA name
# cert_download_url: URL to download the CA certificate in PEM format from
management_import_certification_authorities:
  - caname: "ManagementCA"
    cert_download_url: "https://ca01.{{ organizationDomainName }}/ejbca/publicweb/webdist/certdist?cmd=cachain&caid=966011820&format=pem"
    cert_file_location: /var/tmp/managementca.crt
    superadmincn: "{{ superAdminCn }}"
  - caname: "{{ organizationNameShort }}-Root-CA"
    cert_download_url: "https://ca01.{{ organizationDomainName }}/ejbca/publicweb/webdist/certdist?cmd=cachain&caid=-1905764898&format=pem"
    cert_file_location: "/var/tmp/{{ organizationNameShort }}-Root-CA.crt"
    superadmincn: ""
  - caname: "{{ organizationNameShort }}-Sub-CA"
    cert_download_url: "https://ca01.{{ organizationDomainName }}/ejbca/publicweb/webdist/certdist?cmd=cacert&caid=-127947408&format=pem&level=0"
    cert_file_location: "/var/tmp/{{ organizationNameShort }}-Sub-CA.crt"
    superadmincn: ""

