---

- hosts: ejbcaCaServers
  become: yes
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - include_vars: customer_info/customer_vars.yml
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}"
    ejbca_software_url: "{{ ejbca_software_ee_url }}"
    ejbca_group: ejbca
    ejbca_user: ejbca
  roles:
    - ansible-ejbca-upgrade

- hosts: ejbcaCaServers[0]
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - include_vars: customer_info/customer_vars.yml
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}"
    ejbca_software_url: "{{ ejbca_software_ee_url }}"
    ejbca_group: ejbca
    ejbca_user: ejbca
    - ansible-ejbca-complete-upgrade
  roles:

- hosts: ejbcaRaServers
  become: yes
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - include_vars: customer_info/customer_vars.yml
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_RA"
    ejbca_software_url: "{{ ejbca_software_ra_url }}"
    ejbca_group: ejbcara
    ejbca_user: ejbcara
  roles:
    - ansible-ejbca-upgrade

- hosts: ejbcaRaServers[0]
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - include_vars: customer_info/customer_vars.yml
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_RA"
    ejbca_software_url: "{{ ejbca_software_ra_url }}"
    ejbca_group: ejbcara
    ejbca_user: ejbcara
  roles:
    - ansible-ejbca-complete-upgrade

- hosts: ejbcaVaServers
  become: yes
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - include_vars: customer_info/customer_vars.yml
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_VA"
    ejbca_software_url: "{{ ejbca_software_va_url }}"
    ejbca_group: ejbcava
    ejbca_user: ejbcava
  roles:
    - ansible-ejbca-upgrade

- hosts: ejbcaVaServers[0]
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - include_vars: customer_info/customer_vars.yml
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_VA"
    ejbca_software_url: "{{ ejbca_software_va_url }}"
    ejbca_group: ejbcava
    ejbca_user: ejbcava
  roles:
    - ansible-ejbca-complete-upgrade