---

- name: Install Nginx packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ nginx_packages }}"
  when: (ansible_facts['distribution'] == "CentOS" ) or
        (ansible_facts['distribution'] == "RedHat" ) 
  tags: reverse-proxy