---
# tasks file for ansible-ejbca-certreq-cli

- name: Create End Entities batch style 
  include_tasks: batch_cert_request.yml
  loop: "{{ identity_info }}"
  when: identity_info[0] is defined

- name: Sign CSR End Entities
  include_tasks: csr_cert_sign.yml
  loop: "{{ identity_csr_info }}"
  loop_control:
    loop_var: csr_item
  when: identity_csr_info[0] is defined