---

- name: Check the CRLPeriod for Management & Root CA's
  command: "{{ ejbca_sh }} ca getcafield {{ item.caname }} CRLPeriod"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ management_add_certification_authorities }}"
  register: clrPeriod_check
  changed_when: item.crlPeriod|string not in clrPeriod_check.stdout
  no_log: true

- name: Check the CRLIssueInterval for Management & Root CA's
  command: "{{ ejbca_sh }} ca getcafield {{ item.caname }} CRLIssueInterval"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ management_add_certification_authorities }}"
  register: crlIssueInterval_check
  changed_when: item.crlIssueInterval|string not in crlIssueInterval_check.stdout
  no_log: true

- name: Check the defaultCRLDistPoint for Management & Root CA's
  command: "{{ ejbca_sh }} ca getcafield {{ item.caname }} defaultCRLDistPoint"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ management_add_certification_authorities }}"
  register: defaultCRLDistPoint_check
  changed_when: item.defaultCRLDP|string not in defaultCRLDistPoint_check.stdout
  no_log: true

- name: Check the defaultOCSPServiceLocator for Management & Root CA's
  command: "{{ ejbca_sh }} ca getcafield {{ item.caname }} defaultOCSPServiceLocator"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ management_add_certification_authorities }}"
  register: defaultOCSPServiceLocator_check
  changed_when: item.defaultOCSPServiceLocator|string not in defaultOCSPServiceLocator_check.stdout
  no_log: true

- name: Check the authorityInformationAccess for Management & Root CA's
  command: "{{ ejbca_sh }} ca getcafield {{ item.caname }} authorityInformationAccess"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ management_add_certification_authorities }}"
  register: authorityInformationAccess_check
  changed_when: item.authorityInformationAccess|string not in authorityInformationAccess_check.stdout
  no_log: true

- name: Check the certificateAiaDefaultCaIssuerUri for Management & Root CA's
  command: "{{ ejbca_sh }} ca getcafield {{ item.caname }} certificateAiaDefaultCaIssuerUri"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ management_add_certification_authorities }}"
  register: certificateAiaDefaultCaIssuerUri_check
  changed_when: item.certificateAiaDefaultCaIssuerUri|string not in certificateAiaDefaultCaIssuerUri_check.stdout
  no_log: true

- name: Check the useLdapDnOrder for Management & Root CA's
  command: "{{ ejbca_sh }} ca getcafield {{ item.caname }} useLdapDnOrder"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ management_add_certification_authorities }}"
  register: useLdapDnOrder_check
  changed_when: item.useLdapDnOrder|string not in useLdapDnOrder_check.stdout
  no_log: true

- name: Configure the CRLPeriod for Management & Root CA's
  command: "{{ ejbca_sh }} ca editca {{ item.item.caname }} CRLPeriod {{ item.item.crlPeriod }}"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ clrPeriod_check.results }}"
  when: item.changed
  no_log: true

- name: Configure the CRLIssueInterval for Management & Root CA's
  command: "{{ ejbca_sh }} ca editca {{ item.item.caname }} CRLIssueInterval {{ item.item.crlIssueInterval }}"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ crlIssueInterval_check.results }}"
  when: item.changed
  no_log: true

- name: Configure the defaultCRLDistPoint for Management & Root CA's
  command: "{{ ejbca_sh }} ca editca {{ item.item.caname }} defaultCRLDistPoint {{ item.item.defaultCRLDP }}"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ defaultCRLDistPoint_check.results }}"
  when: item.changed
  no_log: true

- name: Configure the defaultOCSPServiceLocator for Management & Root CA's
  command: "{{ ejbca_sh }} ca editca {{ item.item.caname }} defaultOCSPServiceLocator {{ item.item.defaultOCSPServiceLocator }}"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ defaultOCSPServiceLocator_check.results }}"
  when: item.changed
  no_log: true

- name: Configure the authorityInformationAccess for Management & Root CA's
  command: "{{ ejbca_sh }} ca editca {{ item.item.caname }} authorityInformationAccess {{ item.item.authorityInformationAccess }}"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ authorityInformationAccess_check.results }}"
  when: item.changed
  no_log: true

- name: Configure the certificateAiaDefaultCaIssuerUri for Management & Root CA's
  command: "{{ ejbca_sh }} ca editca {{ item.item.caname }} certificateAiaDefaultCaIssuerUri {{ item.item.certificateAiaDefaultCaIssuerUri }}"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ certificateAiaDefaultCaIssuerUri_check.results }}"
  when: item.changed
  no_log: true

- name: Configure the useLdapDnOrder for Management & Root CA's
  command: "{{ ejbca_sh }} ca editca {{ item.item.caname }} useLdapDnOrder {{ item.item.useLdapDnOrder }}"
  args:
    chdir: "{{ ejbca_home }}"
  become_user: "{{ ejbca_user }}"
  become: yes
  loop: "{{ useLdapDnOrder_check.results }}"
  when: item.changed
  no_log: true

#- name: Create the CRL
#  command: "{{ ejbca_sh }} ca createcrl --caname {{ item.caname }}"
#  args:
#    chdir: "{{ ejbca_home }}"
#  become_user: "{{ ejbca_user }}"
#  become: yes

#- name: Export the CRL
#  command: "{{ ejbca_sh }} ca getcrl --caname {{ item.caname }} -f /opt/web/CRLs/{{ primekey_mgmtCA_ca_crl_name }}"
#  args:
#    chdir: "{{ ejbca_home }}"
#  become_user: "{{ ejbca_user }}"
#  become: yes
#  register: getcrl
