---

- name: Ensure application server is started
  service:
    name: wildfly
    state: started
  when: wildfly_manage_service

- name: Ensure EJBCA EAR file is deployed
  wait_for:
    delay: 30
    #timeout: 335
    path: "{{ wildfly_home }}/standalone/deployments/ejbca.ear.deployed"
    state: present
