---

#- name: Check if timestamp worker exists

- name: Prepare timestamp signer properties file for SignServer
  template:
    src: timestamp.properties.j2
    dest: "{{ signsvr_home }}/conf/tsa-{{ item.id }}.properties"
    owner: "{{ signsrv_user }}"
    group: "{{ signsrv_group }}"
    mode: 0640
  loop: "{{ tsa_signers }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add timestamp signer to SignServer
  command: "{{ signsvr_home }}/bin/signserver setproperties {{ signsvr_home }}/conf/tsa-{{ item.id }}.properties"
  args:
    chdir: "{{ signsvr_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  loop: "{{ tsa_signers }}"
  loop_control:
    label: "{{ item.name }}"

- name: Reload SignServer
  command: "{{ signsvr_home }}/bin/signserver reload {{ item.name }}"
  args:
    chdir: "{{ signsvr_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  loop: "{{ tsa_signers }}"
  loop_control:
    label: "{{ item.name }}"
