---

- hosts: ejbcaVaServersAWS
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: customer_info/aws_vars.yml
  roles:
    #- ansible-role-hostname
    #- ansible-role-mariadb
    #- ansible-ejbca-wildfly
    #- ansible-ejbca-va-prep
    - ansible-ejbca-va-ee

- hosts: ejbcaCaServersAWS
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - include_vars: customer_info/aws_vars.yml
  roles:
    - ansible-ejbca-certreq-cli

- hosts: ejbcaVaServersAWS
  become: yes
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - include_vars: customer_info/aws_vars.yml 
  roles:
    - ansible-ejbca-va-ocsp-bind
    - ansible-ejbca-va-httpd
