---

- name: Export Managment CA cert to file
  command: "{{ ejbca_sh }} ca getcacert --caname ManagementCA -f /var/tmp/managmentca.crt"
  args:
    chdir: "{{ ejbca_home }}"
    creates: /var/tmp/managmentca.crt
  become_user: "{{ ejbca_ra_user }}"
  become: yes

- name: Add Managment CA cert to file to trusted-ca file
  shell: cat /var/tmp/managmentca.crt >> /etc/pki/tls/certs/trusted-ca.crt
