---
# defaults file for ansible-ejbca-ra-prep

ejbca_root_dir: /opt
ejbca_home: "{{ ejbca_root_dir }}/ejbca"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
wildfly_manage_service: true

ejbca_src_link_dir: "{{  ejbca_root_dir }}/ejbca"

organizationName: Solitude
organizationNameShort: "{{ organizationName }}"
organizationDomainName: solitude.skyrim
countryName: US

wildfly_standalone_file: standalone-19.xml.datasource.j2
wildfly_disable_infinispan: true

ejbca_jdbc_driver: https://downloads.mariadb.com/Connectors/java/connector-java-2.5.4/mariadb-java-client-2.5.4.jar
ejbca_jdbc_gen_name: mariadb-java-client.jar

ejbca_ra_manage_user: true
ejbca_ra_group: ejbcara
ejbca_ra_user: ejbcara
ejbca_ra_user_profile: "/home/{{ ejbca_ra_user }}"


# List of repository packages that will be installed by this role
ejbca_ra_packages:
  - unzip
  - java-1.8.0-openjdk-devel.x86_64
  - ant.noarch
  - nss-tools
  - http://repo.okay.com.mx/centos/8/x86_64/release/softhsm-2.4.0-2.el8.x86_64.rpm
  - wget
  - jq

ejbca_ra_softhsm:
  - dir: /opt/softhsm
    src: /usr/lib64/libsofthsm2.so
    dest: /opt/softhsm/hsm_pkcs11.so

# EJBCA audit log database protection configurations
# slot_index: Index of HSM slot used for database integrity protection
# key_label: Label of key used for database integrity protection
# signature_algorithm: Algorithm used to sign database rows
# token_pin: PIN used to access HSM slot. Should be encrypted with Ansible vault
#ejbca_databaseprotection:
#  slot_label: DB_Protect_SLOT
#  key_label: dbProtect00001
#  signature_algorithm: SHA256WithRSA
#  token_pin: "{{ encrypted_databaseprotection_token_pin | default('foo123') }}"
#  hsm_shared_library: /opt/softhsm/hsm_pkcs11.so


ejbca_ra_gen_hsm_slots:
  - slot_name: RA_KeyBinding_SLOT
    slot_so_pin: "{{ encrypted_ocsp_so_token_pin | default('foo123') }}" 
    slot_pin: "{{ encrypted_ocsp_token_pin | default('foo123') }}"
  #- slot_name: KeyBinding_SLOT
  #  slot_so_pin: "{{ encrypted_keybind_so_token_pin | default('foo123') }}"
  #  slot_pin: "{{ encrypted_keybind_token_pin | default('foo123') }}"

# PrimeKey property files
ejbca_templated_properties_files:
  - src: cesecore.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/cesecore.properties"
  - src: database.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/database.properties"
  - src: ejbca.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/ejbca.properties"
  #- src: install.properties.j2
  #  dest: "{{ ejbca_home }}/../ejbca-custom/conf/install.properties"
  - src: web.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/web.properties"
  - src: mail.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/mail.properties"
  #- src: databaseprotection.properties.j2
  #  dest: "{{ ejbca_home }}/../ejbca-custom/conf/databaseprotection.properties"

ejbca_force_build_ear: false

# EJBCA statedump utility source package ZIP file
ejbca_statedump_src: 

# If the statedump utility should be built into EJBCA
ejbca_build_statedump: false
# If the configdump utility should be built into EJBCA
ejbca_build_configdump: false

appsrv_datasources:
  - jndi_name: "java:/EjbcaDS"
    pool_name: ejbcads
    host: 127.0.0.1
    port: 3306
    database: ejbca
    user: ejbca-usr
    password: "{{ encrypted_database_ejbcauser_password | default('ejbca') }}"

#ejbca.properties
ejbca_appserver_home: "{{ wildfly_home }}"
ejbca_productionmode: false
ejbca_allow_external_dynamic_configuration: false
# Password used to protect CMS keystores in the database (CAs CMS signer/enc certificate).
ejbca_ca_cmskeystorepass: "{{ encrypted_ejbca_ca_cmskeystorepass | default('ejbca') }}"
ejbca_cli_defaultusername: ejbca
ejbca_cli_defaultpassword: "{{ encrypted_ejbca_cli_password | default('ejbca') }}"

#cesecore.properties
core_allow_external_dynamic_configuration: false
core_ca_serialnumberoctetsize: 20
core_db_keepjbossserialization: false
core_db_keepinternalcakeystores: false
core_ca_keepocspextendedservice: false

#database.properties
ejbca_db_database_name: mysql
ejbca_db_database_useSeparateCertificateTable: true

#mail.properties
mail_from: "ejbca-donotreply@{{ organizationDomainName }}" 

#web.properties
web_httpserver_external_privhttps: 443
web_reqcertindb: false