---

- hosts: ejbcaCaServers
  gather_facts: false
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: deployment_vars/deploy_vars.yml
  roles:
    - ansible-ejbca-certreq-cli
    - ansible-ejbca-ca-add-sn-to-admin-role

- hosts: docker_hosts
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: deployment_vars/deploy_vars.yml
  roles:
    - ansible-role-docker

- hosts: docker_hosts
  become: no
  become_method: sudo
  pre_tasks:
    - include_vars: deployment_vars/deploy_vars.yml
    - setup:
        filter: ansible_env.HOME
  roles:
    - ansible-ejbca-vault-container


