---

- name: Create local directories
  become: no
  file:
    path: "{{ ejbca_csr_dir_output }}"
    state: directory
  delegate_to: localhost

- name: Copy the {{ item.caname }}_csr.der CSR locally 
  fetch:
    src: "{{ ejbca_home }}/{{ item.caname }}_csr.der"
    dest: "{{ ejbca_csr_dir_output }}/{{ item.caname }}_csr.der"
    flat: yes
  no_log: true
  register: copy_down_csr