---

- name: Generate HSM keys for Peering
  include_tasks: clienttoolbox_key_generation.yml
  loop: "{{ peer_generate_hsm_keys }}"
  loop_control:
    label: "{{ item.slot_identifier }}"
  no_log: true
  tags: clienttoolbox_key_generation
  when: peer_generate_hsm_keys[0] is defined

- name: Check deployment
  include_tasks: check_deployment.yml
  tags: check_deployment
  when: peer_generate_hsm_keys[0] is defined

- name: Create Key Binding
  include_tasks: add_keybinding_ca.yml
  when: use_external_va|bool or use_external_ra|bool or use_external_ss|bool

- name: Create Peer Connector
  include_tasks: add_peer_conn.yml
  when: use_external_va|bool or use_external_ra|bool or use_external_ss|bool
