---

- name: Test that HSM slots are available
  include_tasks: hsm_test.yml
  loop: "{{ test_hsm_slots }}"
  loop_control:
    label: "{{ item.slot_identifier }}"
  no_log: true
  tags: hsm_test
  when: test_hsm_slots[0] is defined

- name: Generate HSM keys
  include_tasks: clienttoolbox_key_generation.yml
  loop: "{{ generate_hsm_keys }}"
  loop_control:
    label: "{{ item.slot_identifier }}"
  no_log: true
  tags: clienttoolbox_key_generation
  when: generate_hsm_keys[0] is defined

- name: Create Key Binding 
  include_tasks: add_keybinding_ca.yml
  when: use_external_va|bool or use_external_ra|bool or use_external_ss|bool

- name: Create Peer Connector
  include_tasks: add_peer_conn.yml
  when: use_external_va|bool or use_external_ra|bool or use_external_ss|bool

- name: Prepare configdump template files
  include_tasks: config_configdump.yml
  when:
    - configdump_directory_structure is defined
    - configdump_import_files is defined

- name: Create external VA services and publisher with configdump
  command: "./configdump.sh import  --ignore-errors --overwrite update --non-interactive continue -l {{ ejbca_home }}/dump/va"
  args:
    chdir: "{{ ejbca_home }}/dist/configdump"
  become: yes 
  become_user: "{{ ejbca_user }}"
  when: use_external_va|bool

- name: Import Approval Profiles
  include_tasks: add_app_profs.yml

- name: Import configdump of profiles, services, & publishers
  command: "./configdump.sh import --ignore-errors --overwrite update --non-interactive continue -l {{ ejbca_home }}/dump/dump3"
  args:
    chdir: "{{ ejbca_home }}/dist/configdump"
  become: yes 
  become_user: "{{ ejbca_user }}"

- name: Create external RA role with configdump
  command: "./configdump.sh import --ignore-errors --overwrite update --non-interactive continue -l {{ ejbca_home }}/dump/ra"
  args:
    chdir: "{{ ejbca_home }}/dist/configdump"
  become: yes 
  become_user: "{{ ejbca_user }}"
  when: use_external_ra|bool