---

- name: Import signed CA certificate
  include_tasks: add_external_signed_ca.yml
  loop: "{{ add_certification_authorities }}"
  when: add_certification_authorities[0] is defined
  no_log: true

- name: Configure CA settings
  include_tasks: config_ca_extensions.yml
  loop: "{{ add_certification_authorities }}"
  no_log: true
  tags: configure_cas_extentions

- name: Configdump import cert profiles, end entity profiles, and services
  command: "./configdump.sh import  --ignore-errors --overwrite update --non-interactive continue -l {{ ejbca_home }}/dump/dump2"
  args:
    chdir: "{{ ejbca_home }}/dist/configdump"
  become: yes 
  become_user: "{{ ejbca_user }}"

- name: Configure EJBCA Enrollment protocols
  include_tasks: config_ejbca_services.yaml

- name: Add end entities
  include_tasks: add_end_entities.yml
  tags: add_end_entities
  when: management_add_end_entities[0] is defined

- name: Add administrators
  include_tasks: add_administrators.yml
  tags: add_administrators
  when: management_add_administrators[0] is defined