---
# tasks file for ansible-ejbca-ca-ee

- name: Deploy Management, Root, & Sub CA
  include_tasks: deploy_mgmt_root_sub.yml
  when:
    - deploy_mgmt_root_sub is defined
    - deploy_mgmt_root_sub|bool

- name: Deploy CA's Subordinated to a Root CA
  include_tasks: deploy_subordinate_ca.yml
  when:
    - deploy_subordinate_ca is defined
    - deploy_subordinate_ca|bool

- name: Complete Import of Externally Signed Subordinated CA & Post CA configuration
  include_tasks: deploy_complete_sub_post_config.yml
  when:
    - deploy_complete_sub_post_config is defined
    - deploy_complete_sub_post_config|bool

- name: Configure Peering on CA node
  include_tasks: deploy_ca_peering_config.yml
  when:
    - deploy_ca_peering_config is defined
    - deploy_ca_peering_config|bool
