---
# defaults file for ansible-ejbca-certreq-cli
ejbca_csr_dir_output: "{{ playbook_dir }}/ejbcaCSR"
ejbca_root_dir: /opt
ejbca_home: "{{ ejbca_root_dir }}/ejbca"
ejbca_sh: "{{ ejbca_home }}/bin/ejbca.sh"
wildfly_install_dir: /opt
wildfly_home: "{{ wildfly_install_dir }}/wildfly"
ejbca_group: ejbca
ejbca_user: ejbca

identity_batch_output_dir: /var/tmp
organizationName: Solitude
organizationNameShort: "{{ organizationName }}"
organizationDomainName: solitude.skyrim
countryName: US

identity_info:
  - dn: "OU=Devices,O={{ organizationName }},C={{ countryName }}"
    name: "ocsp01.{{ organizationDomainName }}"
    full_dn: "C={{ countryName }},O={{ organizationName }},OU=Devices,cn=ocsp01.{{ organizationDomainName }}"
    username: va_httpd_tls
    password: "{{ encrypted_httpd_identity_password | default('foo123') }}"
    altname: "dNSName=ocsp01.{{ organizationDomainName }}"
    certprofile: tlsServerClientAuth
    eeprofile: "tlsServer{{ organizationNameShort }}"
    caname: "{{ organizationNameShort }}-Sub-CA"
    token: PEM
