---

- name: Prepare PKCS11 Slot conf file for SignServer
  template:
    src: pkcs11-crypto.properties.j2
    dest: "{{ signsrv_home }}/conf/p11-{{ item.id }}.properties"
    owner: "{{ signsrv_user }}"
    group: "{{ signsrv_group }}"
    mode: 0640
  loop: "{{ p11_crypto_tokens }}"
  no_log: true

- name: Add PKCS11 Slot for SignServer
  command: "{{ signsrv_home }}/bin/signserver setproperties {{ signsrv_home }}/conf/p11-{{ item.id }}.properties"
  args:
    chdir: "{{ signsrv_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  register: create_p11_slot
  loop: "{{ p11_crypto_tokens }}"
  loop_control:
    label: "{{ item.name }}"
  #no_log: true

- name: Remove the PKCS11 Slot conf file
  lineinfile:
    path: "{{ signsrv_home }}/conf/p11-{{ item.id }}.properties"
    state: absent
    regexp: 'WORKERGENID[0-9]*\.PIN*?'
  loop: "{{ p11_crypto_tokens }}"
  loop_control:
    label: "{{ item.name }}"
  #no_log: true

- name: Reload SignServer
  command: "{{ signsrv_home }}/bin/signserver reload {{ item.id }}"
  args:
    chdir: "{{ signsrv_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  loop: "{{ p11_crypto_tokens }}"
  loop_control:
    label: "{{ item.name }}"

- name: Activate the crypto tokens
  command: "{{ signsrv_home }}/bin/signserver activatecryptotoken {{ item.id }} {{ encrypted_signsrv_token_pin | default('foo123') }}"
  args:
    chdir: "{{ signsrv_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  loop: "{{ p11_crypto_tokens }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true
  failed_when: false

- name: Create a test key on the crypto tokens
  command: "{{ signsrv_home }}/bin/signserver generatekey {{ item.id }} -alias {{ item.testkey_alias }} -keyalg {{ item.testkey_keyalg }} -keyspec {{ item.testkey_keyspec }}"
  args:
    chdir: "{{ signsrv_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  loop: "{{ p11_crypto_tokens }}"
  loop_control:
    label: "{{ item.name }}"