---


- name: Generate private key for signer in PKCS11
  command: "{{ signsrv_home }}/bin/signserver generatekey {{ item.workerid }} -keyalg {{ item.keyalg }} -keyspec {{ item.keysize }} -alias {{ item.keyalias }}"
  args:
    chdir: "{{ signsrv_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  register: generate_p11_keys
  loop: "{{ p11_generate }}"
  loop_control:
    label: "{{ item.name }}"

- name: Genrate CSR for signer from PKCS11 private key
  command: "{{ signsrv_home }}/bin/signserver generatecertreq  {{ item.workerid }} '{{ item.dn }}' {{ item.sig_alg }} /var/tmp/{{ item.name }} -alias {{ item.keyalias }}"
  args:
    chdir: "{{ signsrv_home }}"
  environment:
    APPSRV_HOME: "{{ wildfly_home }}"
  become: yes
  become_user: "{{ signsrv_user }}"
  register: generate_p11_keys
  loop: "{{ p11_generate }}"
  loop_control:
    label: "{{ item.name }}"

- name: Copy certificate to localhost
  become: no
  fetch:
    src: "/var/tmp/{{ item.name }}"
    dest: "{{ ejbca_csr_dir_output }}/{{ item.name }}.csr"
    flat: yes
  loop: "{{ p11_generate }}"
  loop_control:
    label: "{{ item.name}}"
  #when: item.name not in keybinding_exists.stdout

- name: Cleanup the cert files in /var/tmp
  file:
    path: "/var/tmp/{{ item.name }}"
    state: absent
  loop: "{{ p11_generate }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true
  #when: item.name