---
# handlers file for primekeyprep

- name: restart wildfly
  service:
    name: wildfly
    state: restarted

- name: stop wildfly
  service:
    name: wildfly
    state: stopped

- name: start wildfly
  service:
    name: wildfly
    state: started