---

- name: Install OpenJDK Development, unzip, & Ant CentOS/RHEL 8
  dnf:
    name: "{{ ejbca_ra_packages_8 }}"
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") 

- name: Install OpenJDK Development, unzip, & Ant CentOS/RHEL 7
  yum:
    name: "{{ ejbca_ra_packages_7 }}"
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or
        (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") 

- name: Check if ejbca directory exists
  stat:
    path: "{{ ejbca_root_dir }}/{{ ejbca_src_dir_name }}"
  register: ejbca_src_dir

- name: Download and unpack EJBCA RA EE archive
  unarchive:
    src: "{{ ejbca_software_url }}"
    dest: /opt
    remote_src: yes
  when: not ejbca_src_dir.stat.exists
  register: unpacked_ejbca

- name: Create symlink to installed version
  file:
    state: link
    src: "{{ ejbca_root_dir }}/{{ ejbca_src_dir_name }}"
    dest: "{{ ejbca_home }}"

- name: Download the JDBC Driver
  get_url:
    url: "{{ ejbca_jdbc_driver }}"
    owner: "{{ ejbca_ra_user }}"
    group: "{{ ejbca_ra_group }}"
    dest: "{{ wildfly_home }}/standalone/deployments/{{ ejbca_jdbc_gen_name }}"
