---

- name: Check if clientToolBox directory exists
  stat:
    path: "{{ ejbca_home }}/../clientToolBox"
  register: found_clienttoolbox

- name: Ensure clientToolBox is built and copied outside of EJBCA dist folder
  block:
  - name: Ensure clientToolBox is built
    command: ant clientToolBox
    become: yes
    become_user: "{{ ejbca_user }}"
    args:
      chdir: "{{ ejbca_home }}"

  - name: Ensure clientToolBox has been copied outside of EJBCA dist folder
    command: cp -rp "{{ ejbca_home }}/dist/clientToolBox" "{{ ejbca_home }}/.."
  when: unpacked_ejbca.changed or configured_ejbca_properties.changed or removed_ejbca_properties.changed or not found_clienttoolbox.stat.exists